
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[495] =
    {   0,
        0,    0,  114,  112,  111,  110,  112,  112,   92,   98,
       99,  107,  108,   93,  109,   95,  112,   82,   82,   89,
       94,  102,   90,  106,   91,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,  100,  101,
       96,   97,  103,    1,    0,    2,    1,    0,    0,   88,
       83,    1,   83,   82,    0,   85,  105,  104,   86,   86,
       86,   86,   86,   77,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   30,   86,   86,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   45,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,    1,    0,    1,    1,    1,
        0,    0,    2,    1,    1,   87,    0,    0,    1,    1,
        1,   83,   83,    0,   83,   85,   28,   86,   86,   86,
       27,   80,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   40,   86,   63,   86,
       86,   57,   86,   86,   86,   86,   86,   12,   86,   86,
       86,   86,   54,   86,   86,   86,   86,   86,   86,   86,

       86,   61,   86,   86,   86,   67,   86,   86,   86,   86,
       86,   86,   86,    1,    1,    3,    3,    3,    0,    0,
        1,    1,   86,   86,   86,   86,   41,   86,   78,   86,
       86,   86,   35,   86,   86,   81,   86,   86,   13,   86,
       86,   86,   86,    9,   86,   86,   86,   39,   86,   16,
       76,   86,   86,   56,   86,    0,   86,    0,   86,   86,
       65,   86,   86,   86,   86,   86,   44,   46,   86,   86,
       59,   86,   55,   86,   66,   86,   51,   86,   86,   86,
       64,   86,    6,    0,   88,   86,   86,    4,   86,   86,
       86,   79,   86,   86,   86,   86,   86,   86,   86,   60,

       38,   86,   86,   86,   86,   86,   22,   86,    0,   86,
        0,   86,   86,   86,   86,   86,   86,   25,   86,   86,
       86,   75,   58,   86,   62,   86,   86,   86,    8,    0,
       87,   86,    0,   47,   86,   86,   86,   11,   86,   10,
       86,   37,   86,   31,   86,    0,   86,   15,   86,   86,
        0,    0,    0,   86,   18,   20,   14,   86,   42,   86,
       86,   86,   17,   29,   86,   52,    0,   86,    0,   33,
       86,   34,   36,   86,   86,   86,    0,   86,   86,   86,
        0,    0,    0,   86,   86,   86,   86,   50,   53,    0,
       86,    0,   71,   24,   86,   68,   73,   86,   19,   86,

        0,   74,    0,    0,   43,   86,   49,    0,   70,    0,
        0,   86,   86,   86,    0,    0,    0,   48,    0,    0,
        0,   86,   86,   86,   26,    0,    0,    0,    0,    0,
       86,    0,   86,    0,   32,    0,    0,   72,   86,    0,
       69,    0,    0,    0,   86,    0,    0,    0,    0,    7,
        0,    0,    0,   21,    0,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    0,   23,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   84,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,    1,   51,    1,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   40,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,    1,   79,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[80] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    5,    1,    5,    6,    6,    1,    1,    1,
        1,    1,    1,    7,    7,    7,    7,    7,    7,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    9,
        9,   10,    7,    7,    7,    7,    7,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[508] =
    {   0,
        0,    0, 1009, 1076, 1076, 1076,  985,   74,  994, 1076,
     1076, 1076, 1076, 1076,   75, 1076,   80,   80,   84, 1076,
     1076,  965, 1076,  949, 1076,   72,   83,   79,  132,   35,
       99,   42,   65,   87,   43,   76,   74,  101,   91,   98,
      131,    0,  123,  151,  199,  139,  160,  164, 1076, 1076,
     1076, 1076, 1076,  226,  159,    0,  960,  957,  952,  951,
      198,  235,  233,  237,  246,    0, 1076, 1076,    0,  130,
      139,  229,  164,  179,  187,  181,  206,  132,  230,  230,
      139,  253,  227,  234,  242,  241,  251,  249,  251,  253,
      255,  260,  254,    0,  283,  261,  255,  280,  276,  261,

      278,  266,  282,  281,  293,  298,  305,  303,  313,  300,
      314,  295,  312,  317,  311,  321,  318,  319,  333,  343,
      329,  338,  335,  336,  338,  388,  382,  402,  408,    0,
      407,  393,    0,    0,  953,  950,  948,  946,  413,  421,
      423,  404,  424,  426, 1076,    0,    0,  393,  334,  387,
        0,    0,  414,  422,  413,  407,  408,  417,  431,  428,
      425,  432,  439,  424,  443,  430,  446,  438,  439,  458,
      451,  462,  446,  875,  448,  464,  455,  459,  458,  469,
      460,    0,  476,  944,  477,  940,  470,    0,  483,  482,
      484,  485,    0,  479,  483,  485,  480,  496,  478,  499,

      501,    0,  497,  509,  514,  499,  508,  519,  504,  531,
      504,  511,  524,  559,  567, 1076,  582,  584,  937,  935,
      588,  590,  532,  533,  542,  535,    0,  567,    0,  573,
      559,  560,    0,  568,  563,    0,  576,  578,    0,  589,
      573,  591,  578,    0,  579,  584,  865,    0,  584,    0,
        0,  588,  586,    0,  591,  607,  604,  597,  622,  611,
        0,  615,  628,  620,  621,  631,    0,  619,  634,  630,
        0,  640,    0,  619,    0,  639,    0,  642,  640,  635,
        0,  646,  829,  822, 1076,  647,  805,    0,  636,  657,
      650,  657,  658,  668,  665,  657,  674,  669,  666,    0,

        0,  673,  735,  654,  666,  688,    0,  681,  669,  721,
      693,  678,  692,  700,  683,  695,  698,    0,  687,  688,
      698,    0,    0,  710,    0,  698,  719,  702,    0,  707,
     1076,  726,  722,    0,  715,  718,  718,    0,  726,    0,
      736,    0,  735,    0,  727,  741,  643,    0,  743,  746,
      739,  749,  736,  730,    0,    0,    0,  738,    0,  758,
      751,  742,    0,    0,  745,    0,  760,  750,  757,    0,
      754,    0,    0,  754,  626,  764,  759,  553,  774,  773,
      768,  767,  773,  616,  776,  784,  795,    0,    0,  784,
      798,  792,  611,    0,  783,    0, 1076,  537,    0,  800,

      791, 1076,  804,  805,    0,  801,    0,  806,    0,  802,
      808,  805,  506,  799,  808,  810,  826,    0,  826,  831,
      832,  831,  558,  836, 1076,  834,  824,  841,  834,  829,
      836,  849,  855,  846, 1076,  861,  854, 1076,  862,  863,
        0,  857,  854,  861,  859,  855,  560,  867,  874,    0,
      484,  871,  870, 1076,  472,  878,  875,  427,  880, 1076,
      453,  885,  887,  878,  894, 1076,  877,  374,  370,  355,
      382,  895,  903,  887,  309,  307,  301,  268,  901,  908,
      891,  160,  158,  153,  143,  122,   91,   74,   55,   51,
       44,   30, 1076, 1076,  964,  972,  977,  987,  997, 1007,

     1017, 1025, 1035, 1040, 1047, 1057, 1065
    } ;

static yyconst flex_int16_t yy_def[508] =
    {   0,
      494,    1,  494,  494,  494,  494,  494,  495,  496,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  494,  494,
      494,  494,  494,  498,  499,  500,  501,  502,  496,  494,
      494,  503,  494,  494,  494,  504,  494,  494,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  498,  494,  498,  498,  505,
      499,  499,  500,  501,  501,  494,  502,  506,  503,  503,
      503,  494,  494,  494,  494,  504,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  498,  498,  494,  499,  499,  507,  506,
      503,  503,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  494,  497,  494,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  507,  494,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  494,  497,
      494,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  494,
      494,  497,  494,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  494,  497,  497,  497,  497,
      494,  494,  494,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  494,  497,  494,  497,
      497,  497,  497,  497,  497,  497,  494,  497,  497,  497,
      494,  494,  494,  497,  497,  497,  497,  497,  497,  494,
      497,  494,  497,  497,  497,  497,  494,  497,  497,  497,

      494,  494,  494,  494,  497,  497,  497,  494,  497,  494,
      494,  497,  497,  497,  494,  494,  494,  497,  494,  494,
      494,  497,  497,  497,  494,  494,  494,  494,  494,  494,
      497,  494,  497,  494,  494,  494,  494,  494,  497,  494,
      497,  494,  494,  494,  497,  494,  494,  494,  494,  497,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,    0,  494,  494,  494,  494,  494,  494,

      494,  494,  494,  494,  494,  494,  494
    } ;

static yyconst flex_uint16_t yy_nxt[1156] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   42,   42,   42,   49,
       50,    4,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   43,   44,
       45,   46,   47,   48,   42,   42,   42,   51,   52,   54,
       56,   87,   92,   55,   96,   62,   56,   56,   57,   55,
       61,   61,   93,   63,   57,   64,   64,   63,   70,   64,

       64,   71,   78,   97,  493,   98,   72,   65,   73,   87,
       92,   65,   96,   74,   75,   94,   79,   76,  492,   80,
       77,   93,   88,   95,   99,  491,   66,   70,  100,  490,
       71,   78,   97,   89,   98,   72,   65,   73,  101,   90,
       65,   74,   91,   75,   94,   79,   76,   80,  489,   77,
      105,   88,   95,   99,   66,   81,  147,  100,  102,   82,
      106,  127,   89,   83,  132,  488,  101,   90,  148,   84,
       91,  103,   85,  156,  104,   86,  107,  119,  108,  105,
      120,  160,  121,  122,   81,  147,  109,  102,   82,  106,
      151,  123,   83,  110,  124,  125,  487,  148,   84,  103,

       85,  156,  104,   86,  152,  107,  119,  108,  120,  160,
      121,   63,  122,   61,   61,  109,  153,  486,  154,  151,
      123,  110,  111,  124,  125,   65,  112,  485,  127,  128,
      113,  129,  484,  152,  483,  130,  114,  127,  140,  115,
      141,  116,  117,  155,  134,  153,  118,  154,  142,  142,
       63,  111,   64,   64,   65,  112,  143,  159,  144,  113,
       65,  145,  145,  149,   65,  114,  157,  115,  164,  116,
      117,  150,  155,  158,  118,  130,  130,  165,  161,  166,
      479,  167,  168,  169,  134,  134,  159,  162,  170,   65,
      171,  172,  149,   65,  163,  157,  164,  173,  178,  150,

      174,  158,  179,  184,  185,  165,  186,  161,  166,  167,
      175,  168,  169,  187,  182,  180,  162,  170,  183,  171,
      172,  181,  163,  188,  176,  177,  173,  178,  174,  189,
      179,  184,  190,  185,  186,  191,  194,  192,  196,  175,
      195,  197,  187,  182,  180,  193,  183,  198,  199,  181,
      200,  188,  176,  177,  201,  202,  203,  204,  189,  205,
      208,  190,  211,  212,  191,  194,  192,  196,  195,  197,
      206,  224,  209,  193,  207,  478,  198,  199,  210,  200,
      213,  477,  201,  476,  202,  203,  204,  216,  205,  208,
      127,  211,  212,  214,  472,  127,  216,  130,  132,  206,

      224,  209,  215,  207,  127,  128,  210,  214,  213,  127,
      127,  130,  217,  129,  225,  127,  215,  130,  221,  142,
      142,  218,  134,  127,  140,  127,  221,  222,  141,  471,
      134,   65,  134,  223,  145,  222,  145,  130,  130,  145,
      145,  145,  145,  225,  470,  226,  227,  228,  469,  229,
      230,  130,  130,  231,  232,  233,  234,  130,  130,  235,
       65,  223,  134,  134,  236,  463,  237,  238,  239,  240,
      134,  134,  134,  134,  226,  227,  228,  229,  230,  241,
      242,  243,  231,  232,  233,  234,  244,  245,  235,  246,
      248,  249,  250,  236,  237,  251,  238,  239,  240,  252,

      253,  461,  254,  255,  257,  259,  260,  241,  242,  261,
      243,  262,  263,  264,  265,  244,  245,  246,  248,  266,
      249,  250,  267,  268,  251,  269,  270,  252,  271,  253,
      254,  272,  255,  257,  259,  260,  273,  274,  261,  275,
      262,  263,  264,  265,  276,  277,  458,  278,  266,  281,
      267,  282,  268,  269,  283,  270,  279,  271,  455,  286,
      272,  127,  280,  452,  129,  273,  274,  275,  130,  127,
      432,  289,  214,  276,  277,  278,  130,  281,  287,  282,
      423,  215,  288,  283,  127,  279,  127,  132,  286,  217,
      127,  280,  127,  141,  290,  221,  291,  134,  218,  134,

      289,  292,  293,  294,  222,  295,  287,  296,  130,  130,
      288,  413,  297,  298,  411,  299,  130,  130,  300,  404,
      301,  302,  303,  290,  305,  291,  306,  398,  307,  292,
      293,  308,  294,  295,  309,  311,  296,  134,  134,  134,
      134,  297,  298,  299,  310,  312,  313,  300,  301,  302,
      314,  303,  305,  315,  316,  306,  307,  317,  318,  308,
      319,  324,  320,  309,  311,  321,  322,  323,  325,  326,
      327,  328,  310,  329,  312,  313,  332,  395,  334,  314,
      335,  336,  315,  316,  337,  338,  317,  318,  319,  324,
      320,  339,  340,  341,  321,  322,  323,  325,  326,  327,

      328,  342,  329,  343,  345,  332,  334,  344,  348,  335,
      336,  349,  350,  337,  338,  351,  353,  378,  354,  355,
      339,  340,  341,  356,  352,  357,  358,  359,  347,  360,
      342,  361,  343,  345,  362,  344,  348,  363,  346,  364,
      349,  350,  365,  351,  366,  353,  354,  367,  355,  368,
      369,  370,  356,  357,  371,  358,  359,  360,  372,  361,
      373,  374,  375,  362,  376,  377,  363,  364,  379,  380,
      381,  365,  366,  382,  385,  367,  383,  384,  368,  369,
      370,  386,  387,  371,  388,  389,  372,  390,  392,  373,
      374,  375,  391,  376,  377,  393,  394,  379,  380,  381,

      396,  399,  382,  385,  383,  384,  397,  400,  333,  401,
      386,  387,  388,  389,  402,  403,  390,  392,  405,  406,
      391,  407,  408,  393,  394,  409,  410,  331,  412,  396,
      399,  414,  330,  415,  397,  416,  400,  401,  417,  418,
      419,  421,  402,  403,  420,  422,  405,  424,  406,  425,
      407,  408,  426,  427,  409,  410,  412,  428,  429,  430,
      414,  415,  431,  433,  416,  434,  436,  417,  418,  419,
      421,  435,  420,  422,  437,  424,  438,  425,  439,  440,
      426,  441,  427,  442,  443,  444,  428,  429,  430,  445,
      446,  431,  433,  447,  434,  436,  448,  449,  453,  435,

      450,  451,  437,  454,  438,  456,  439,  457,  440,  459,
      441,  460,  442,  443,  444,  462,  464,  465,  445,  446,
      466,  467,  447,  468,  448,  473,  449,  453,  450,  451,
      474,  480,  454,  475,  456,  481,  457,  482,  459,  304,
      460,  285,  136,  258,  462,  464,  465,  256,  466,  247,
      467,  468,   60,  136,  473,  219,  135,  138,   60,  474,
      480,  475,  136,  135,  481,  482,   58,   58,   58,   68,
       58,   58,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   69,   69,   69,   67,   69,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  131,  131,  131,

       60,  131,  131,  131,  131,   53,  131,  133,  494,  133,
      133,  133,  133,  133,  133,  133,  133,  134,  494,  134,
      134,  134,  134,  134,  134,  134,  134,  137,  494,  494,
      137,  137,  137,  494,  137,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  146,  146,  130,  494,  130,
      130,  130,  130,  130,  130,  130,  130,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  284,  494,  494,
      284,  284,  284,  494,  284,    3,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494
    } ;

static yyconst flex_int16_t yy_chk[1156] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       15,   30,   32,    8,   35,   17,    8,   15,    8,   17,
       15,   15,   33,   18,   17,   18,   18,   19,   26,   19,

       19,   26,   28,   36,  492,   37,   26,   18,   26,   30,
       32,   19,   35,   26,   27,   34,   28,   27,  491,   28,
       27,   33,   31,   34,   38,  490,   18,   26,   39,  489,
       26,   28,   36,   31,   37,   26,   18,   26,   40,   31,
       19,   26,   31,   27,   34,   28,   27,   28,  488,   27,
       43,   31,   34,   38,   18,   29,   70,   39,   41,   29,
       43,   55,   31,   29,   55,  487,   40,   31,   71,   29,
       31,   41,   29,   78,   41,   29,   44,   46,   44,   43,
       46,   81,   46,   47,   29,   70,   44,   41,   29,   43,
       73,   47,   29,   44,   48,   48,  486,   71,   29,   41,

       29,   78,   41,   29,   74,   44,   46,   44,   46,   81,
       46,   61,   47,   61,   61,   44,   75,  485,   76,   73,
       47,   44,   45,   48,   48,   61,   45,  484,   54,   54,
       45,   54,  483,   74,  482,   54,   45,   62,   62,   45,
       62,   45,   45,   77,   62,   75,   45,   76,   63,   63,
       64,   45,   64,   64,   61,   45,   65,   80,   65,   45,
       63,   65,   65,   72,   64,   45,   79,   45,   83,   45,
       45,   72,   77,   79,   45,   54,   54,   84,   82,   85,
      478,   86,   87,   88,   62,   62,   80,   82,   89,   63,
       90,   91,   72,   64,   82,   79,   83,   92,   96,   72,

       93,   79,   97,  100,  101,   84,  102,   82,   85,   86,
       95,   87,   88,  103,   99,   98,   82,   89,   99,   90,
       91,   98,   82,  104,   95,   95,   92,   96,   93,  105,
       97,  100,  106,  101,  102,  107,  109,  108,  111,   95,
      110,  112,  103,   99,   98,  108,   99,  113,  113,   98,
      114,  104,   95,   95,  115,  116,  117,  118,  105,  119,
      121,  106,  123,  124,  107,  109,  108,  111,  110,  112,
      120,  149,  122,  108,  120,  477,  113,  113,  122,  114,
      125,  476,  115,  475,  116,  117,  118,  127,  119,  121,
      126,  123,  124,  126,  471,  132,  127,  126,  132,  120,

      149,  122,  126,  120,  128,  128,  122,  128,  125,  131,
      129,  128,  131,  129,  150,  139,  128,  129,  139,  142,
      142,  131,  139,  140,  140,  141,  140,  139,  141,  470,
      140,  142,  141,  148,  143,  140,  144,  126,  126,  143,
      143,  144,  144,  150,  469,  153,  154,  155,  468,  156,
      157,  128,  128,  158,  159,  160,  161,  129,  129,  162,
      142,  148,  139,  139,  163,  461,  164,  165,  166,  167,
      140,  140,  141,  141,  153,  154,  155,  156,  157,  168,
      169,  170,  158,  159,  160,  161,  171,  172,  162,  173,
      175,  176,  177,  163,  164,  178,  165,  166,  167,  179,

      180,  458,  181,  183,  185,  187,  189,  168,  169,  190,
      170,  191,  192,  194,  195,  171,  172,  173,  175,  196,
      176,  177,  197,  198,  178,  199,  200,  179,  201,  180,
      181,  203,  183,  185,  187,  189,  204,  205,  190,  206,
      191,  192,  194,  195,  207,  208,  455,  209,  196,  211,
      197,  212,  198,  199,  213,  200,  210,  201,  451,  223,
      203,  214,  210,  447,  214,  204,  205,  206,  214,  215,
      423,  226,  215,  207,  208,  209,  215,  211,  224,  212,
      413,  215,  225,  213,  217,  210,  218,  217,  223,  218,
      221,  210,  222,  221,  228,  222,  230,  221,  218,  222,

      226,  231,  232,  234,  222,  235,  224,  237,  214,  214,
      225,  398,  238,  240,  393,  241,  215,  215,  242,  384,
      243,  245,  246,  228,  249,  230,  252,  378,  253,  231,
      232,  255,  234,  235,  256,  258,  237,  221,  221,  222,
      222,  238,  240,  241,  257,  259,  260,  242,  243,  245,
      262,  246,  249,  263,  264,  252,  253,  265,  266,  255,
      268,  274,  268,  256,  258,  269,  270,  272,  276,  278,
      279,  280,  257,  282,  259,  260,  286,  375,  289,  262,
      290,  291,  263,  264,  292,  293,  265,  266,  268,  274,
      268,  294,  295,  296,  269,  270,  272,  276,  278,  279,

      280,  297,  282,  298,  302,  286,  289,  299,  305,  290,
      291,  306,  308,  292,  293,  309,  311,  347,  312,  313,
      294,  295,  296,  314,  310,  315,  316,  317,  304,  319,
      297,  320,  298,  302,  321,  299,  305,  324,  303,  326,
      306,  308,  327,  309,  328,  311,  312,  330,  313,  332,
      333,  335,  314,  315,  336,  316,  317,  319,  337,  320,
      339,  341,  343,  321,  345,  346,  324,  326,  349,  350,
      351,  327,  328,  352,  358,  330,  353,  354,  332,  333,
      335,  360,  361,  336,  362,  365,  337,  367,  369,  339,
      341,  343,  368,  345,  346,  371,  374,  349,  350,  351,

      376,  379,  352,  358,  353,  354,  377,  380,  287,  381,
      360,  361,  362,  365,  382,  383,  367,  369,  385,  386,
      368,  387,  390,  371,  374,  391,  392,  284,  395,  376,
      379,  400,  283,  401,  377,  403,  380,  381,  404,  406,
      408,  411,  382,  383,  410,  412,  385,  414,  386,  415,
      387,  390,  416,  417,  391,  392,  395,  419,  420,  421,
      400,  401,  422,  424,  403,  426,  428,  404,  406,  408,
      411,  427,  410,  412,  429,  414,  430,  415,  431,  432,
      416,  433,  417,  434,  436,  437,  419,  420,  421,  439,
      440,  422,  424,  442,  426,  428,  443,  444,  448,  427,

      445,  446,  429,  449,  430,  452,  431,  453,  432,  456,
      433,  457,  434,  436,  437,  459,  462,  463,  439,  440,
      464,  465,  442,  467,  443,  472,  444,  448,  445,  446,
      473,  479,  449,  474,  452,  480,  453,  481,  456,  247,
      457,  220,  219,  186,  459,  462,  463,  184,  464,  174,
      465,  467,  138,  137,  472,  136,  135,   60,   59,  473,
      479,  474,   58,   57,  480,  481,  495,  495,  495,   24,
      495,  495,  496,  496,  496,  496,  496,  496,  496,  496,
      496,  496,  497,  497,  497,   22,  497,  498,  498,  498,
      498,  498,  498,  498,  498,  498,  498,  499,  499,  499,

        9,  499,  499,  499,  499,    7,  499,  500,    3,  500,
      500,  500,  500,  500,  500,  500,  500,  501,    0,  501,
      501,  501,  501,  501,  501,  501,  501,  502,    0,    0,
      502,  502,  502,    0,  502,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  504,  504,  505,    0,  505,
      505,  505,  505,  505,  505,  505,  505,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  507,    0,    0,
      507,  507,  507,    0,  507,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,

      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494,  494,  494,  494,  494,  494,
      494,  494,  494,  494,  494
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cassandra.l"
#line 2 "cassandra.l"
	#include<stdio.h>
	#include"cassandra.h"
	

#line 896 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 18 "cassandra.l"

#line 1116 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 495 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1076 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "cassandra.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "cassandra.l"
{}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 21 "cassandra.l"
{}       
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "cassandra.l"
{return ALTER;}                                                                                
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "cassandra.l"
{return WITH_REPLICATION;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "cassandra.l"
{return WITH;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "cassandra.l"
{return DURABLE_WRITES;}                             
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "cassandra.l"
{return WHERE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "cassandra.l"
{return FROM;}                                        
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "cassandra.l"
{ return DELETE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "cassandra.l"
{ return CREATE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "cassandra.l"
{ return PUT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "cassandra.l"
{ return DROP;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "cassandra.l"
{return SELECT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "cassandra.l"
{ return INSERT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "cassandra.l"
{ return INTO;}	
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "cassandra.l"
{ return UPDATE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "cassandra.l"
{ return RENAME;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "cassandra.l"
{ return KEYSPACE;}	
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "cassandra.l"
{ return SCHEMA;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "cassandra.l"
{return ALLOW;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "cassandra.l"
{return LIMIT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "cassandra.l"
{return PER;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "cassandra.l"
{return DISTINCT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "cassandra.l"
{return TABLE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "cassandra.l"
{ return NOT_EXISTS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "cassandra.l"
{ return AND;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "cassandra.l"
{return ADD;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "cassandra.l"
{ return VALUES;}		
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "cassandra.l"
{ return IF;}	
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "cassandra.l"
{ return EXISTS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "cassandra.l"
{ return PRIMARY_KEY;}		
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "cassandra.l"
{ return BOOLEAN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "cassandra.l"
{ return COUNTER;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "cassandra.l"
{ return DATE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "cassandra.l"
{ return DECIMAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "cassandra.l"
{ return DOUBLE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "cassandra.l"
{ return FLOAT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "cassandra.l"
{ return INET;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "cassandra.l"
{ return INT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "cassandra.l"
{return BLOB;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "cassandra.l"
{return STRING;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "cassandra.l"
{ return SMALLINT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "cassandra.l"
{ return TEXT;}					
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "cassandra.l"
{return TO_TOKEN;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "cassandra.l"
{ return TIME;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "cassandra.l"
{return BIGINT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 66 "cassandra.l"
{ return TIMESTAMP;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 67 "cassandra.l"
{ return TIMEUUID;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 68 "cassandra.l"
{ return TINYINT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 69 "cassandra.l"
{ return UUID;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 70 "cassandra.l"
{ return VARINT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 "cassandra.l"
{ return VARCHAR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 72 "cassandra.l"
{return SET;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 "cassandra.l"
{ return TYPE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 74 "cassandra.l"
{ return LIST;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 75 "cassandra.l"
{ return MAP;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 76 "cassandra.l"
{ return TUPLE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 77 "cassandra.l"
{ return TRUE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 78 "cassandra.l"
{ return FALSE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 79 "cassandra.l"
{ return TTL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 80 "cassandra.l"
{ return USING;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 81 "cassandra.l"
{return KEY;}	
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 82 "cassandra.l"
{return VIEW;}	
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 83 "cassandra.l"
{return ROLE;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 84 "cassandra.l"
{return USER;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 85 "cassandra.l"
{return USE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 86 "cassandra.l"
{return FUNCTION;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 87 "cassandra.l"
{return MATERIALIZED;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 88 "cassandra.l"
{return AGGREGATE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 89 "cassandra.l"
{return CONTAINS;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 90 "cassandra.l"
{return CONT_KEY;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 91 "cassandra.l"
{return GROUP;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 92 "cassandra.l"
{return ORDER;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 93 "cassandra.l"
{return TOKEN;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 94 "cassandra.l"
{return JSON;}/* lexical dial oussama*/
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 95 "cassandra.l"
{return AS;}  //14/12/2016
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 96 "cassandra.l"
{ return CAST;} 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 97 "cassandra.l"
{ return COUNT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 98 "cassandra.l"
{return ASC;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 99 "cassandra.l"
{return DESC;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 100 "cassandra.l"
{ return INUMBER;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 101 "cassandra.l"
{ return DNUMBER;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 102 "cassandra.l"
{ return UUID_TOKEN;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 103 "cassandra.l"
{ return BLOB_TOKEN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 104 "cassandra.l"
{ return UNQUOTED_IDF;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 105 "cassandra.l"
{return QUOTED_IDF;}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 106 "cassandra.l"
{return STRING_TOKEN;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 107 "cassandra.l"
{ return TWOP;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 108 "cassandra.l"
{return EQ;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 109 "cassandra.l"
{return QST;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 110 "cassandra.l"
{ return APOST;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 111 "cassandra.l"
{ return VIRG;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 112 "cassandra.l"
{ return PVIRG;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 113 "cassandra.l"
{return POINT;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 114 "cassandra.l"
{ return ACOLO;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 115 "cassandra.l"
{ return ACOLF;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 116 "cassandra.l"
{return POPEN;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 117 "cassandra.l"
{return PCLOSE;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 118 "cassandra.l"
{return CROPEN;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 119 "cassandra.l"
{return CRCLOSE;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 120 "cassandra.l"
{ return LESSER;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 121 "cassandra.l"
{return DIFF;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 122 "cassandra.l"
{return BIGGEREQ;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 123 "cassandra.l"
{return LESSEREQ;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 124 "cassandra.l"
{ return BIGGER;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 125 "cassandra.l"
{ return MULT;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 126 "cassandra.l"
{return PLUS;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 127 "cassandra.l"
{return MINUS;}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 128 "cassandra.l"
{return ENTER;}
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 129 "cassandra.l"
/* caractère vide */
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 130 "cassandra.l"
{return ERRORLEX;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 132 "cassandra.l"
ECHO;
	YY_BREAK
#line 1742 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 495 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 495 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 494);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 132 "cassandra.l"




